// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCamdUfFKi-lRpH4iJ9rOufA7hrUujEDDk',
    appId: '1:149923852085:web:32002177b88da8ab7ea67c',
    messagingSenderId: '149923852085',
    projectId: 'pot-proj',
    authDomain: 'pot-proj.firebaseapp.com',
    storageBucket: 'pot-proj.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJeoqxDTEJDM3nmKnCNYdxeE4WtOdAROw',
    appId: '1:149923852085:android:76154cb29bc9f9e97ea67c',
    messagingSenderId: '149923852085',
    projectId: 'pot-proj',
    storageBucket: 'pot-proj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC90YA5o1uT33mH4mVGPS1QRD0X1Hl1heA',
    appId: '1:149923852085:ios:b38b6dfa3ee52eda7ea67c',
    messagingSenderId: '149923852085',
    projectId: 'pot-proj',
    storageBucket: 'pot-proj.firebasestorage.app',
    iosBundleId: 'com.example.pot',
  );
}
